1. Load the dataset

In [4]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv(r"E:\data_analytics_projects\datasets\indian_e-commerce_sales\raw_data\customers.csv")

In [9]:
#To check first 5 rows
df.head()

,Customer_ID,Customer_Name,Gender,Age,Age_Group,Date_of_Birth,Email,Phone,City,State,Pincode,Registration_Date,Customer_Tier,Total_Orders,Total_Spent
0,CUST00000001,Akash Agarwal,male,48,46-55,1/13/1977,akashagarwal@gmail.com,-9625151920,Patiala,Punjab,122521,1/28/2024,Gold,5,40098.48
1,CUST00000002,Farhan Rahman,male,73,65+,1/20/1952,farhanrahman@gmail.com,-8593009374,Durgapur,West Bengal,226518,8/25/2023,Platinum,8,63676.24
2,CUST00000003,Suresh Kumar,male,31,26-35,1/9/1994,sureshkumar755@gmail.com,-7935884683,Gurugram,Haryana,520400,8/30/2023,Silver,0,0.00
3,CUST00000004,Aditya Pandey,male,41,36-45,1/12/1984,adityapandey@outlook.com,-9015045981,Kolkata,West Bengal,735356,3/11/2024,Platinum,5,288324.84
4,CUST00000005,Hina Khan,female,53,46-55,1/15/1972,hinakhan433@gmail.com,-8813094180,Noida,UP,985141,4/19/2024,Platinum,4,69265.75

In [10]:
#To check the last 5 rows
df.tail()

,Customer_ID,Customer_Name,Gender,Age,Age_Group,Date_of_Birth,Email,Phone,City,State,Pincode,Registration_Date,Customer_Tier,Total_Orders,Total_Spent
39995,CUST00039996,Swati Joshi,female,43,36-45,1/12/1982,swatijoshi369@outlook.com,-7611105942,Mysore,Karnataka,544799,6/26/2023,Platinum,4,137030.99
39996,CUST00039997,Nikhil Patel,male,33,26-35,1/10/1992,nikhilpatel@gmail.com,-9819454103,Mumbai,Maharashtra,113783,10/3/2023,Platinum,8,193564.72
39997,CUST00039998,Akash Yadav,male,24,18-25,1/7/2001,akashyadav85@yahoo.com,-9602738558,Ahmedabad,Gujarat,927070,4/12/2024,Platinum,6,191316.63
39998,CUST00039999,Salman Ansari,male,52,46-55,1/14/1973,salmanansari844@yahoo.com,-9209459809,Mysore,Karnataka,313975,10/15/2023,Silver,2,6482.53
39999,CUST00040000,Ahmed Ahmed,male,34,26-35,1/10/1991,ahmedahmed@outlook.com,-8093119968,Ahmedabad,Gujarat,551113,8/19/2023,Platinum,8,216922.80

In [11]:
#To see the whole table
df.info

<bound method DataFrame.info of         Customer_ID  Customer_Name  Gender  Age Age_Group Date_of_Birth  \
0      CUST00000001  Akash Agarwal    male   48     46-55     1/13/1977
1      CUST00000002  Farhan Rahman    male   73       65+     1/20/1952
2      CUST00000003   Suresh Kumar    male   31     26-35      1/9/1994
3      CUST00000004  Aditya Pandey    male   41     36-45     1/12/1984
4      CUST00000005      Hina Khan  female   53     46-55     1/15/1972
...             ...            ...     ...  ...       ...           ...
39995  CUST00039996    Swati Joshi  female   43     36-45     1/12/1982
39996  CUST00039997   Nikhil Patel    male   33     26-35     1/10/1992
39997  CUST00039998    Akash Yadav    male   24     18-25      1/7/2001
39998  CUST00039999  Salman Ansari    male   52     46-55     1/14/1973
39999  CUST00040000    Ahmed Ahmed    male   34     26-35     1/10/1991

                           Email       Phone       City        State  Pincode  \
0         akashagarwal@gmail.com -9625151920    Patiala       Punjab   122521
1         farhanrahman@gmail.com -8593009374   Durgapur  West Bengal   226518
2       sureshkumar755@gmail.com -7935884683   Gurugram      Haryana   520400
3       adityapandey@outlook.com -9015045981    Kolkata  West Bengal   735356
4          hinakhan433@gmail.com -8813094180      Noida           UP   985141
...                          ...         ...        ...          ...      ...
39995  swatijoshi369@outlook.com -7611105942     Mysore    Karnataka   544799
39996      nikhilpatel@gmail.com -9819454103     Mumbai  Maharashtra   113783
39997     akashyadav85@yahoo.com -9602738558  Ahmedabad      Gujarat   927070
39998  salmanansari844@yahoo.com -9209459809     Mysore    Karnataka   313975
39999     ahmedahmed@outlook.com -8093119968  Ahmedabad      Gujarat   551113

      Registration_Date Customer_Tier  Total_Orders  Total_Spent
0             1/28/2024          Gold             5     40098.48
1             8/25/2023      Platinum             8     63676.24
2             8/30/2023        Silver             0         0.00
3             3/11/2024      Platinum             5    288324.84
4             4/19/2024      Platinum             4     69265.75
...                 ...           ...           ...          ...
39995         6/26/2023      Platinum             4    137030.99
39996         10/3/2023      Platinum             8    193564.72
39997         4/12/2024      Platinum             6    191316.63
39998        10/15/2023        Silver             2      6482.53
39999         8/19/2023      Platinum             8    216922.80

[40000 rows x 15 columns]>

In [12]:
#To see the no.cols and rows
df.shape

(40000, 15)

In [13]:
#To show cols name
df.columns

Index(['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'Age_Group',
       'Date_of_Birth', 'Email', 'Phone', 'City', 'State', 'Pincode',
       'Registration_Date', 'Customer_Tier', 'Total_Orders', 'Total_Spent'],
      dtype='object')

2. Check Data types

In [14]:
df.dtypes

Customer_ID           object
Customer_Name         object
Gender                object
Age                    int64
Age_Group             object
Date_of_Birth         object
Email                 object
Phone                  int64
City                  object
State                 object
Pincode                int64
Registration_Date     object
Customer_Tier         object
Total_Orders           int64
Total_Spent          float64
dtype: object

3. Check Missing values

In [15]:
#TO see missing values in each cols
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Gender               0
Age                  0
Age_Group            0
Date_of_Birth        0
Email                0
Phone                0
City                 0
State                0
Pincode              0
Registration_Date    0
Customer_Tier        0
Total_Orders         0
Total_Spent          0
dtype: int64

In [16]:
#Check whether dataset has any missing values
df.isnull().values.sum()

0

In [17]:
#To count missing value percentage
(df.isnull().sum() / len(df)) * 100

Customer_ID          0.0
Customer_Name        0.0
Gender               0.0
Age                  0.0
Age_Group            0.0
Date_of_Birth        0.0
Email                0.0
Phone                0.0
City                 0.0
State                0.0
Pincode              0.0
Registration_Date    0.0
Customer_Tier        0.0
Total_Orders         0.0
Total_Spent          0.0
dtype: float64

4. Check for Duplicates records

In [18]:
#To find Duplicates records
df.duplicated().sum()

0

In [19]:
#To show no. of unique records
df.nunique()

Customer_ID          40000
Customer_Name          927
Gender                   2
Age                     58
Age_Group                6
Date_of_Birth           58
Email                26567
Phone                40000
City                    39
State                   10
Pincode              39077
Registration_Date      366
Customer_Tier            3
Total_Orders            18
Total_Spent          39522
dtype: int64

In [23]:
#To see no. cusotmer_id are unique
df["Customer_ID"].nunique()

40000

In [26]:
#compare with total_rows
len(df)
#[NOTE}: IF both rows and customer_id {Any column} have same no. of rows then it is unique records

40000

In [28]:
#To how many customer_id duplicated
df["Customer_ID"].duplicated().nunique()

1

5. Clean text columns

In [30]:
#To check value of gender
df["Gender"].value_counts()

Gender
male      20003
female    19997
Name: count, dtype: int64

In [31]:
#To check value of age
df["Age"].value_counts()

Age
29    1466
34    1445
30    1433
31    1419
28    1393
27    1393
33    1389
26    1381
32    1376
35    1364
25    1284
23    1268
20    1264
24    1236
21    1214
18    1214
19    1204
22    1192
43     837
37     828
40     828
38     820
44     812
39     803
41     784
45     779
42     766
36     754
47     508
55     507
46     506
53     503
49     490
48     485
50     473
51     467
52     457
54     445
61     255
62     255
56     249
65     248
58     247
64     243
63     242
59     241
57     239
60     218
70      89
67      84
72      81
71      80
66      76
68      76
74      75
69      73
75      73
73      69
Name: count, dtype: int64

In [32]:
#To count value of age_group
df["Age_Group"].value_counts()

Age_Group
26-35    14059
18-25     9876
36-45     8011
46-55     4841
56-65     2437
65+        776
Name: count, dtype: int64

In [33]:
#To count value of e-mail
df["Email"].value_counts()

Email
simransingh@yahoo.com        16
meghakumar@gmail.com         16
riyagupta@yahoo.com          16
shreyapandey@yahoo.com       15
nishasharma@gmail.com        15
                             ..
nehamishra31@yahoo.com        1
poojakumar455@yahoo.com       1
simransharma359@yahoo.com     1
saifrahman120@outlook.com     1
salmanansari844@yahoo.com     1
Name: count, Length: 26567, dtype: int64

In [34]:
#To count value of city
df["City"].value_counts()

City
New Delhi     1105
Madurai       1104
Howrah        1099
Kanpur        1075
Patiala       1071
Varanasi      1071
Chennai       1069
Amritsar      1067
Alwar         1057
Kolkata       1041
Palwal        1038
Surat         1037
Agra          1036
Dwarka        1036
Vadodara      1033
Sohna         1032
Thane         1031
Mysore        1031
Mangalore     1027
Lucknow       1026
Jaipur        1022
Panipat       1022
Mumbai        1021
Gurugram      1018
Nagpur        1016
Faridabad     1014
Noida         1010
Durgapur      1000
Jodhpur        998
Coimbatore     997
Ludhiana       995
Udaipur        994
Rajkot         986
Kota           986
Pune           982
Delhi NCR      975
Ahmedabad      970
Bangalore      958
Jalandhar      950
Name: count, dtype: int64

In [36]:
#To count value of state
df["State"].value_counts()

State
UP             5218
Haryana        5124
Rajasthan      5057
Punjab         4083
Maharashtra    4050
Gujarat        4026
Tamil Nadu     3170
West Bengal    3140
Delhi          3116
Karnataka      3016
Name: count, dtype: int64

In [37]:
#To count value of customer_tier
df["Customer_Tier"].value_counts()

Customer_Tier
Platinum    27349
Gold         6692
Silver       5959
Name: count, dtype: int64

In [41]:
#To remove unnecessary space between txts
text_cols = [
    "Customer_ID",
    "Customer_Name",
    "Gender",
    "Age_Group",
    "Email",
    "City",
    "State",
    "Customer_Tier"
]
for colm in text_cols:
        df[colm] = df[colm].str.strip()

In [52]:
#Standardize suitable categorical columns
df["Gender"] = df["Gender"].str.title()
df["Age_Group"] = df["Age_Group"].str.title()
df["City"] = df["City"].str.title()
df["State"] = df["State"].str.title()
df["Customer_Tier"] = df["Customer_Tier"].str.title()

In [53]:
df["Email"] = df["Email"].str.strip().str.lower()

6. Check Age

In [54]:
df["Age"].describe()

count    40000.000000
mean        35.306225
std         12.581443
min         18.000000
25%         26.000000
50%         33.000000
75%         43.000000
max         75.000000
Name: Age, dtype: float64

In [55]:
df["Age"].min()

18

In [57]:
df["Age"].max()

75

7. Check Phone no. Column

In [59]:
df["Phone"] = df["Phone"].astype("string")
df["Phone"].head()

0    -9625151920
1    -8593009374
2    -7935884683
3    -9015045981
4    -8813094180
Name: Phone, dtype: string

In [60]:
df["Phone"] .str.len().value_counts()

Phone
11    40000
Name: count, dtype: Int64

8. Check Pincode

In [62]:
df["Pincode"] = df["Pincode"].astype("string")
df["Pincode"].str.len().value_counts()

Pincode
6    40000
Name: count, dtype: Int64

9. Convert Date Columns

In [63]:
#To change the data type of date_of_birth and registration_date
df["Date_of_Birth"] = pd.to_datetime(df["Date_of_Birth"], errors="coerce")
df["Registration_Date"] = pd.to_datetime(df["Registration_Date"], errors="coerce")
#[NOTE]: In case columns contains an invalid dates likes"abc", "unknown" etc. so use error="coerce"(it will converts as NaT(Not a Time),
#If you find problamatic records then use given code
#code: df[df["Date_of_Birth].isna()
#code: df[df["Registration_Date"].isnaa()
df.dtypes

Customer_ID                  object
Customer_Name                object
Gender                       object
Age                           int64
Age_Group                    object
Date_of_Birth        datetime64[ns]
Email                        object
Phone                string[python]
City                         object
State                        object
Pincode              string[python]
Registration_Date    datetime64[ns]
Customer_Tier                object
Total_Orders                  int64
Total_Spent                 float64
dtype: object

In [66]:
df.dtypes

Customer_ID                  object
Customer_Name                object
Gender                       object
Age                           int64
Age_Group                    object
Date_of_Birth        datetime64[ns]
Email                        object
Phone                string[python]
City                         object
State                        object
Pincode              string[python]
Registration_Date    datetime64[ns]
Customer_Tier                object
Total_Orders                  int64
Total_Spent                 float64
dtype: object

10. Check Date Problems

In [74]:
#For Date_of_Birth
df["Date_of_Birth"].isnull().sum()

Timestamp('2007-01-06 00:00:00')

In [75]:
df["Date_of_Birth"].min()

Timestamp('1950-01-20 00:00:00')

In [76]:
df["Date_of_Birth"].max()

Timestamp('2007-01-06 00:00:00')

In [77]:
#For Registration_Date
df["Registration_Date"].isnull().sum()

0

In [78]:
df["Registration_Date"].min()

Timestamp('2023-06-01 00:00:00')

In [79]:
df["Registration_Date"].max()

Timestamp('2024-05-31 00:00:00')

11. Check Numeric Columns

In [80]:
df[["Age", "Total_Orders", "Total_Spent"]].describe()

                Age  Total_Orders   Total_Spent
count  40000.000000  40000.000000   40000.00000
mean      35.306225      5.003475  118539.15886
std       12.581443      2.232485  106205.42346
min       18.000000      0.000000       0.00000
25%       26.000000      3.000000   37814.14750
50%       33.000000      5.000000   90059.66000
75%       43.000000      6.000000  169958.41750
max       75.000000     17.000000  890131.55000

In [81]:
#To check suspicious/negative values
(df["Total_Orders"] < 0).sum()

0

In [82]:
(df["Total_Spent"] < 0).sum()

0

12. Handle Missing Values

In [83]:
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Gender               0
Age                  0
Age_Group            0
Date_of_Birth        0
Email                0
Phone                0
City                 0
State                0
Pincode              0
Registration_Date    0
Customer_Tier        0
Total_Orders         0
Total_Spent          0
dtype: int64

In [87]:
#Check column by column
df["Customer_ID"].isnull().sum()
df["Customer_Name"].isnull().sum()
df["Gender"].isnull().sum()
df["Age"].isnull().sum()
df["Age_Group"].isnull().sum()
df["Date_of_Birth"].isnull().sum()
df["Email"].isnull().sum()
df["Phone"].isnull().sum()
df["City"].isnull().sum()
df["State"].isnull().sum()
df["Pincode"].isnull().sum()
df["Registration_Date"].isnull().sum()
df["Customer_Tier"].isnull().sum()
df["Total_Orders"].isnull().sum()
df["Total_Spent"].isnull().sum()

0

13. Remove Duplicates Record

In [94]:
#To check the duplicates records first
df.duplicated().sum()

#If available then remove
df = df.drop_duplicates()

#To verify
df.duplicated().sum()
df.

0

In [96]:
df.to_csv(r"E:\data_analytics_projects\datasets\indian_e-commerce_sales\cleaned_data\customers.csv")