1. Load the Dataset

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"E:\data_analytics_projects\datasets\indian_e-commerce_sales\raw_data\sales.csv")
df.info

<bound method DataFrame.info of              Order_ID   Customer_ID  Product_ID  Order_Date Order_Time  \
0       ORD0000000001  CUST00014303  PROD001017  2026-06-07   08:20:00
1       ORD0000000002  CUST00034253  PROD000703  2025-02-04   20:05:00
2       ORD0000000003  CUST00000421  PROD000318  2026-03-12   14:59:00
3       ORD0000000004  CUST00026507  PROD000213  2025-01-27   14:33:00
4       ORD0000000005  CUST00009418  PROD001437  2024-06-30   07:19:00
...               ...           ...         ...         ...        ...
249995  ORD0000249996  CUST00008137  PROD001818  2024-10-06   19:17:00
249996  ORD0000249997  CUST00027003  PROD000955  2024-08-28   05:26:00
249997  ORD0000249998  CUST00027511  PROD001894  2025-12-09   13:44:00
249998  ORD0000249999  CUST00022175  PROD001950  2025-05-01   18:24:00
249999  ORD0000250000  CUST00001621  PROD001213  2025-10-28   02:01:00

       Delivery_Date  Quantity  Unit_Price  Order_Value  Shipping_Cost  ...  \
0         2026-06-10         1     2622.46      2622.46            0.0  ...
1         2025-02-07         1    90258.00     90258.00            0.0  ...
2         2026-03-19         1     3536.50      3536.50            0.0  ...
3         2025-02-02         1    34081.56     34081.56            0.0  ...
4         2024-07-02         2    69021.17    138042.34            0.0  ...
...              ...       ...         ...          ...            ...  ...
249995    2024-10-08         1     1827.96      1827.96            0.0  ...
249996    2024-08-31         1     4040.86      4040.86            0.0  ...
249997    2025-12-12         2    10516.60     21033.20            0.0  ...
249998    2025-05-05         1     7847.77      7847.77            0.0  ...
249999    2025-10-30         1    18454.82     18454.82            0.0  ...

       Coupon_Discount  Total_Amount  Payment_Mode Order_Status Rating  \
0                  0.0       2622.46           COD    Delivered    NaN
1                  0.0      90258.00           COD    Delivered    4.0
2                  0.0       3536.50           UPI   Processing    NaN
3                 50.0      34031.56   Credit Card    Delivered    NaN
4                  0.0     138042.34           UPI    Delivered    NaN
...                ...           ...           ...          ...    ...
249995             0.0       1827.96           COD   Processing    NaN
249996             0.0       4040.86           UPI    Delivered    3.0
249997             0.0      21033.20           UPI    Delivered    4.0
249998             0.0       7847.77           UPI    Delivered    5.0
249999             0.0      18454.82    Debit Card    Delivered    3.0

               Review_Text       City        State Customer_Age  \
0                      NaN    Chennai   Tamil Nadu           43
1             Nice quality   Durgapur  West Bengal           22
2                      NaN    Patiala       Punjab           41
3                      NaN     Rajkot      Gujarat           29
4                      NaN      Surat      Gujarat           39
...                    ...        ...          ...          ...
249995                 NaN      Sohna      Haryana           37
249996     Could be better  Mangalore    Karnataka           34
249997     Value for money  Delhi NCR        Delhi           21
249998  Excellent product!   Varanasi           UP           26
249999     Average product     Rajkot      Gujarat           35

        Customer_Age_Group
0                    36-45
1                    18-25
2                    36-45
3                    26-35
4                    36-45
...                    ...
249995               36-45
249996               26-35
249997               18-25
249998               26-35
249999               26-35

[250000 rows x 21 columns]>

In [3]:
df.head()

,Order_ID,Customer_ID,Product_ID,Order_Date,Order_Time,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,...,Coupon_Discount,Total_Amount,Payment_Mode,Order_Status,Rating,Review_Text,City,State,Customer_Age,Customer_Age_Group
0,ORD0000000001,CUST00014303,PROD001017,2026-06-07,08:20:00,2026-06-10,1,2622.46,2622.46,0.0,...,0.0,2622.46,COD,Delivered,NaN,NaN,Chennai,Tamil Nadu,43,36-45
1,ORD0000000002,CUST00034253,PROD000703,2025-02-04,20:05:00,2025-02-07,1,90258.00,90258.00,0.0,...,0.0,90258.00,COD,Delivered,4.0,Nice quality,Durgapur,West Bengal,22,18-25
2,ORD0000000003,CUST00000421,PROD000318,2026-03-12,14:59:00,2026-03-19,1,3536.50,3536.50,0.0,...,0.0,3536.50,UPI,Processing,NaN,NaN,Patiala,Punjab,41,36-45
3,ORD0000000004,CUST00026507,PROD000213,2025-01-27,14:33:00,2025-02-02,1,34081.56,34081.56,0.0,...,50.0,34031.56,Credit Card,Delivered,NaN,NaN,Rajkot,Gujarat,29,26-35
4,ORD0000000005,CUST00009418,PROD001437,2024-06-30,07:19:00,2024-07-02,2,69021.17,138042.34,0.0,...,0.0,138042.34,UPI,Delivered,NaN,NaN,Surat,Gujarat,39,36-45

In [4]:
df.tail()

,Order_ID,Customer_ID,Product_ID,Order_Date,Order_Time,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,...,Coupon_Discount,Total_Amount,Payment_Mode,Order_Status,Rating,Review_Text,City,State,Customer_Age,Customer_Age_Group
249995,ORD0000249996,CUST00008137,PROD001818,2024-10-06,19:17:00,2024-10-08,1,1827.96,1827.96,0.0,...,0.0,1827.96,COD,Processing,NaN,NaN,Sohna,Haryana,37,36-45
249996,ORD0000249997,CUST00027003,PROD000955,2024-08-28,05:26:00,2024-08-31,1,4040.86,4040.86,0.0,...,0.0,4040.86,UPI,Delivered,3.0,Could be better,Mangalore,Karnataka,34,26-35
249997,ORD0000249998,CUST00027511,PROD001894,2025-12-09,13:44:00,2025-12-12,2,10516.60,21033.20,0.0,...,0.0,21033.20,UPI,Delivered,4.0,Value for money,Delhi NCR,Delhi,21,18-25
249998,ORD0000249999,CUST00022175,PROD001950,2025-05-01,18:24:00,2025-05-05,1,7847.77,7847.77,0.0,...,0.0,7847.77,UPI,Delivered,5.0,Excellent product!,Varanasi,UP,26,26-35
249999,ORD0000250000,CUST00001621,PROD001213,2025-10-28,02:01:00,2025-10-30,1,18454.82,18454.82,0.0,...,0.0,18454.82,Debit Card,Delivered,3.0,Average product,Rajkot,Gujarat,35,26-35

In [5]:
df.shape

(250000, 21)

In [6]:
df.describe()

,Quantity,Unit_Price,Order_Value,Shipping_Cost,Coupon_Discount,Total_Amount,Rating,Customer_Age
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,120030.000000,250000.000000
mean,1.249580,19202.477645,23967.862192,4.911971,250.001146,23722.773017,4.399400,35.309416
std,0.535689,26720.495176,37629.320529,18.141581,1399.928532,37267.644163,0.663915,12.574524
min,1.000000,26.130000,26.130000,0.000000,0.000000,-21.560000,3.000000,18.000000
25%,1.000000,1551.550000,1825.890000,0.000000,0.000000,1803.900000,4.000000,26.000000
50%,1.000000,7208.930000,8411.160000,0.000000,0.000000,8339.490000,4.000000,33.000000
75%,1.000000,24433.270000,28612.810000,0.000000,0.000000,28344.920000,5.000000,43.000000
max,3.000000,136973.330000,410919.990000,90.000000,41092.000000,410919.990000,5.000000,75.000000

In [7]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Product_ID', 'Order_Date', 'Order_Time',
       'Delivery_Date', 'Quantity', 'Unit_Price', 'Order_Value',
       'Shipping_Cost', 'Coupon_Code', 'Coupon_Discount', 'Total_Amount',
       'Payment_Mode', 'Order_Status', 'Rating', 'Review_Text', 'City',
       'State', 'Customer_Age', 'Customer_Age_Group'],
      dtype='object')

2. Check Data types

In [8]:
df.dtypes

Order_ID               object
Customer_ID            object
Product_ID             object
Order_Date             object
Order_Time             object
Delivery_Date          object
Quantity                int64
Unit_Price            float64
Order_Value           float64
Shipping_Cost         float64
Coupon_Code            object
Coupon_Discount       float64
Total_Amount          float64
Payment_Mode           object
Order_Status           object
Rating                float64
Review_Text            object
City                   object
State                  object
Customer_Age            int64
Customer_Age_Group     object
dtype: object

In [9]:
df.isnull().sum()

Order_ID                   0
Customer_ID                0
Product_ID                 0
Order_Date                 0
Order_Time                 0
Delivery_Date              0
Quantity                   0
Unit_Price                 0
Order_Value                0
Shipping_Cost              0
Coupon_Code           199815
Coupon_Discount            0
Total_Amount               0
Payment_Mode               0
Order_Status               0
Rating                129970
Review_Text           129970
City                       0
State                      0
Customer_Age               0
Customer_Age_Group         0
dtype: int64

In [10]:
df.duplicated().sum()

0

In [11]:
df["Order_Date"].duplicated().sum()

249240

In [12]:
df["Order_Date"].nunique()

760

In [13]:
df.nunique()

Order_ID              250000
Customer_ID            39914
Product_ID              2000
Order_Date               760
Order_Time              1440
Delivery_Date            765
Quantity                   3
Unit_Price              2000
Order_Value             5968
Shipping_Cost           3938
Coupon_Code                3
Coupon_Discount         4407
Total_Amount           31014
Payment_Mode               4
Order_Status               5
Rating                     3
Review_Text                9
City                      39
State                     10
Customer_Age              58
Customer_Age_Group         6
dtype: int64

In [14]:
df.isnull().values.sum()

459755

In [15]:
(df.isnull().sum() / len(df)) * 100

Order_ID               0.000
Customer_ID            0.000
Product_ID             0.000
Order_Date             0.000
Order_Time             0.000
Delivery_Date          0.000
Quantity               0.000
Unit_Price             0.000
Order_Value            0.000
Shipping_Cost          0.000
Coupon_Code           79.926
Coupon_Discount        0.000
Total_Amount           0.000
Payment_Mode           0.000
Order_Status           0.000
Rating                51.988
Review_Text           51.988
City                   0.000
State                  0.000
Customer_Age           0.000
Customer_Age_Group     0.000
dtype: float64

In [16]:
missing_val = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing_%": (df.isnull().sum() / len(df) * 100).round(2)
})
missing_val

                    Missing Count  Missing_%
Order_ID                        0       0.00
Customer_ID                     0       0.00
Product_ID                      0       0.00
Order_Date                      0       0.00
Order_Time                      0       0.00
Delivery_Date                   0       0.00
Quantity                        0       0.00
Unit_Price                      0       0.00
Order_Value                     0       0.00
Shipping_Cost                   0       0.00
Coupon_Code                199815      79.93
Coupon_Discount                 0       0.00
Total_Amount                    0       0.00
Payment_Mode                    0       0.00
Order_Status                    0       0.00
Rating                     129970      51.99
Review_Text                129970      51.99
City                            0       0.00
State                           0       0.00
Customer_Age                    0       0.00
Customer_Age_Group              0       0.00

3. Check Data types

In [17]:
df.dtypes

Order_ID               object
Customer_ID            object
Product_ID             object
Order_Date             object
Order_Time             object
Delivery_Date          object
Quantity                int64
Unit_Price            float64
Order_Value           float64
Shipping_Cost         float64
Coupon_Code            object
Coupon_Discount       float64
Total_Amount          float64
Payment_Mode           object
Order_Status           object
Rating                float64
Review_Text            object
City                   object
State                  object
Customer_Age            int64
Customer_Age_Group     object
dtype: object

In [18]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors="coerce")
df["Delivery_Date"] = pd.to_datetime(df["Delivery_Date"], errors="coerce")

In [19]:
df["Order_Time"] = pd.to_datetime(df["Order_Time"], format="%H:%M:%S", errors="coerce").dt.time

In [20]:
df[["Order_Date", "Order_Time", "Delivery_Date"]].head()

  Order_Date Order_Time Delivery_Date
0 2026-06-07   08:20:00    2026-06-10
1 2025-02-04   20:05:00    2025-02-07
2 2026-03-12   14:59:00    2026-03-19
3 2025-01-27   14:33:00    2025-02-02
4 2024-06-30   07:19:00    2024-07-02

In [21]:
df[["Order_Date", "Order_Time", "Delivery_Date"]].dtypes

Order_Date       datetime64[ns]
Order_Time               object
Delivery_Date    datetime64[ns]
dtype: object

4. Check problem for the Dates

In [22]:
df["Order_Date"].isnull().sum()

0

In [23]:
df["Order_Date"].min()

Timestamp('2024-06-01 00:00:00')

In [24]:
df["Order_Date"].max()

Timestamp('2026-06-30 00:00:00')

In [25]:
df["Delivery_Date"].min()

Timestamp('2024-06-03 00:00:00')

In [26]:
df["Delivery_Date"].max()

Timestamp('2026-07-07 00:00:00')

In [27]:
raw_sales = pd.read_csv(r"E:\data_analytics_projects\datasets\indian_e-commerce_sales\raw_data\sales.csv")
raw_sales["Order_Time"].head(10)

0    08:20:00
1    20:05:00
2    14:59:00
3    14:33:00
4    07:19:00
5    11:56:00
6    10:32:00
7    17:46:00
8    12:19:00
9    07:45:00
Name: Order_Time, dtype: object

In [28]:
df.dtypes

Order_ID                      object
Customer_ID                   object
Product_ID                    object
Order_Date            datetime64[ns]
Order_Time                    object
Delivery_Date         datetime64[ns]
Quantity                       int64
Unit_Price                   float64
Order_Value                  float64
Shipping_Cost                float64
Coupon_Code                   object
Coupon_Discount              float64
Total_Amount                 float64
Payment_Mode                  object
Order_Status                  object
Rating                       float64
Review_Text                   object
City                          object
State                         object
Customer_Age                   int64
Customer_Age_Group            object
dtype: object

In [53]:
raw_sales["Order_Time"].unique()[::20]

array(['08:20:00', '07:47:00', '22:30:00', '08:04:00', '23:30:00',
       '08:49:00', '09:25:00', '13:52:00', '00:28:00', '14:12:00',
       '17:14:00', '00:19:00', '13:44:00', '12:34:00', '11:41:00',
       '03:44:00', '15:23:00', '18:52:00', '03:00:00', '22:24:00',
       '11:37:00', '11:47:00', '20:55:00', '00:06:00', '05:28:00',
       '11:48:00', '06:28:00', '09:38:00', '15:55:00', '23:49:00',
       '12:39:00', '09:07:00', '14:32:00', '14:29:00', '03:36:00',
       '18:48:00', '05:30:00', '21:05:00', '08:33:00', '11:07:00',
       '16:47:00', '05:32:00', '01:30:00', '08:12:00', '21:10:00',
       '11:43:00', '04:23:00', '03:56:00', '21:53:00', '22:34:00',
       '07:07:00', '23:24:00', '06:14:00', '19:41:00', '09:34:00',
       '04:51:00', '05:19:00', '17:50:00', '07:16:00', '17:15:00',
       '17:01:00', '18:02:00', '12:01:00', '12:55:00', '19:13:00',
       '14:38:00', '13:16:00', '04:05:00', '05:05:00', '10:36:00',
       '18:11:00', '16:43:00'], dtype=object)

In [29]:
df["Order_Time"] = pd.to_datetime(raw_sales["Order_Time"], format="%H:%M:%S", errors="coerce").dt.time

In [30]:
df["Order_Time"].head()

0    08:20:00
1    20:05:00
2    14:59:00
3    14:33:00
4    07:19:00
Name: Order_Time, dtype: object

In [31]:
df[["Order_Date","Order_Time", "Delivery_Date"]].head()

  Order_Date Order_Time Delivery_Date
0 2026-06-07   08:20:00    2026-06-10
1 2025-02-04   20:05:00    2025-02-07
2 2026-03-12   14:59:00    2026-03-19
3 2025-01-27   14:33:00    2025-02-02
4 2024-06-30   07:19:00    2024-07-02

5. Check Numeric Columns

In [60]:
df.dtypes

Order_ID                      object
Customer_ID                   object
Product_ID                    object
Order_Date            datetime64[ns]
Order_Time                    object
Delivery_Date         datetime64[ns]
Quantity                       int64
Unit_Price                   float64
Order_Value                  float64
Shipping_Cost                float64
Coupon_Code                   object
Coupon_Discount              float64
Total_Amount                 float64
Payment_Mode                  object
Order_Status                  object
Rating                       float64
Review_Text                   object
City                          object
State                         object
Customer_Age                   int64
Customer_Age_Group            object
dtype: object

In [32]:
df["Quantity"].isnull().sum()

0

In [33]:
df["Quantity"].duplicated().sum()

249997

In [34]:
(df["Quantity"] < 0).sum()

0

In [35]:
(df["Unit_Price"] < 0).sum()

0

In [36]:
(df["Order_Value"] < 0).sum()

0

In [37]:
(df["Shipping_Cost"] < 0).sum()

0

In [38]:
(df[["Total_Amount", "Coupon_Discount", "Rating", "Customer_Age"]] < 0).sum()

Total_Amount       5
Coupon_Discount    0
Rating             0
Customer_Age       0
dtype: int64

In [39]:
(df["Total_Amount"] < 0).sum()
df.head()

,Order_ID,Customer_ID,Product_ID,Order_Date,Order_Time,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,...,Coupon_Discount,Total_Amount,Payment_Mode,Order_Status,Rating,Review_Text,City,State,Customer_Age,Customer_Age_Group
0,ORD0000000001,CUST00014303,PROD001017,2026-06-07,08:20:00,2026-06-10,1,2622.46,2622.46,0.0,...,0.0,2622.46,COD,Delivered,NaN,NaN,Chennai,Tamil Nadu,43,36-45
1,ORD0000000002,CUST00034253,PROD000703,2025-02-04,20:05:00,2025-02-07,1,90258.00,90258.00,0.0,...,0.0,90258.00,COD,Delivered,4.0,Nice quality,Durgapur,West Bengal,22,18-25
2,ORD0000000003,CUST00000421,PROD000318,2026-03-12,14:59:00,2026-03-19,1,3536.50,3536.50,0.0,...,0.0,3536.50,UPI,Processing,NaN,NaN,Patiala,Punjab,41,36-45
3,ORD0000000004,CUST00026507,PROD000213,2025-01-27,14:33:00,2025-02-02,1,34081.56,34081.56,0.0,...,50.0,34031.56,Credit Card,Delivered,NaN,NaN,Rajkot,Gujarat,29,26-35
4,ORD0000000005,CUST00009418,PROD001437,2024-06-30,07:19:00,2024-07-02,2,69021.17,138042.34,0.0,...,0.0,138042.34,UPI,Delivered,NaN,NaN,Surat,Gujarat,39,36-45

In [81]:
df[df["Total_Amount"] < 0]

,Order_ID,Customer_ID,Product_ID,Order_Date,Order_Time,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,...,Coupon_Discount,Total_Amount,Payment_Mode,Order_Status,Rating,Review_Text,City,State,Customer_Age,Customer_Age_Group
84204,ORD0000084205,CUST00032702,PROD000209,2026-06-26,23:15:00,2026-07-01,1,35.57,35.57,62.36,...,100.0,-2.07,UPI,Delivered,4.0,Good product,Kanpur,UP,60,56-65
182883,ORD0000182884,CUST00012430,PROD000978,2026-01-22,19:32:00,2026-01-24,1,26.13,26.13,52.31,...,100.0,-21.56,COD,Delivered,5.0,Excellent product!,Jaipur,Rajasthan,38,36-45
207695,ORD0000207696,CUST00027671,PROD000978,2026-03-07,00:19:00,2026-03-10,1,26.13,26.13,62.56,...,100.0,-11.31,UPI,Delivered,5.0,Highly recommended!,Pune,Maharashtra,60,56-65
216234,ORD0000216235,CUST00032966,PROD000978,2025-05-19,00:46:00,2025-05-25,1,26.13,26.13,57.40,...,100.0,-16.47,COD,Delivered,4.0,Good product,Gurugram,Haryana,51,46-55
249820,ORD0000249821,CUST00010179,PROD000209,2025-03-26,07:04:00,2025-03-31,1,35.57,35.57,52.45,...,100.0,-11.98,UPI,Cancelled,NaN,NaN,Alwar,Rajasthan,43,36-45

In [43]:
df["Quantity"].isnull().sum()
df["Unit_Price"].isnull().sum()
df["Order_Value"].isnull().sum()
df["Shipping_Cost"].isnull().sum()
df["Coupon_Discount"].isnull().sum()
df["Total_Amount"].isnull().sum()
df["Rating"].isnull().sum()
df["Customer_Age"].isnull().sum()

0

6. Clean Text Column

In [45]:
df[["Order_ID", "Customer_ID", "Product_ID", "Payment_Mode", "Order_Status", "Review_Text", "City", "State", "Customer_Age_Group"]].value_counts()

Order_ID       Customer_ID   Product_ID  Payment_Mode  Order_Status  Review_Text         City      State        Customer_Age_Group
ORD0000000002  CUST00034253  PROD000703  COD           Delivered     Nice quality        Durgapur  West Bengal  18-25                 1
ORD0000167123  CUST00010828  PROD001236  Debit Card    Delivered     Excellent product!  Sohna     Haryana      46-55                 1
ORD0000167147  CUST00029093  PROD000253  UPI           Delivered     Nice quality        Panipat   Haryana      18-25                 1
ORD0000167146  CUST00039668  PROD001174  COD           Delivered     Amazing quality!    Varanasi  UP           46-55                 1
ORD0000167144  CUST00012062  PROD000797  COD           Delivered     Nice quality        Gurugram  Haryana      18-25                 1
                                                                                                                                     ..
ORD0000083416  CUST00027389  PROD000662  UPI           Delivered     Amazing quality!    Madurai   Tamil Nadu   46-55                 1
ORD0000083411  CUST00026820  PROD001308  COD           Delivered     Excellent product!  Rajkot    Gujarat      36-45                 1
ORD0000083410  CUST00010382  PROD001858  UPI           Delivered     Excellent product!  Agra      UP           26-35                 1
ORD0000083406  CUST00036305  PROD000395  UPI           Delivered     Could be better     Noida     UP           18-25                 1
ORD0000250000  CUST00001621  PROD001213  Debit Card    Delivered     Average product     Rajkot    Gujarat      26-35                 1
Name: count, Length: 120030, dtype: int64

In [47]:
text_clm = [
    "Order_ID", 
    "Customer_ID", 
    "Product_ID", 
    "Payment_Mode", 
    "Order_Status", 
    "Review_Text", 
    "City", 
    "State", 
    "Customer_Age_Group"
]
for columns in text_clm:
    df[columns] = df[columns].str.strip()
df.head()

,Order_ID,Customer_ID,Product_ID,Order_Date,Order_Time,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,...,Coupon_Discount,Total_Amount,Payment_Mode,Order_Status,Rating,Review_Text,City,State,Customer_Age,Customer_Age_Group
0,ORD0000000001,CUST00014303,PROD001017,2026-06-07,08:20:00,2026-06-10,1,2622.46,2622.46,0.0,...,0.0,2622.46,COD,Delivered,NaN,NaN,Chennai,Tamil Nadu,43,36-45
1,ORD0000000002,CUST00034253,PROD000703,2025-02-04,20:05:00,2025-02-07,1,90258.00,90258.00,0.0,...,0.0,90258.00,COD,Delivered,4.0,Nice quality,Durgapur,West Bengal,22,18-25
2,ORD0000000003,CUST00000421,PROD000318,2026-03-12,14:59:00,2026-03-19,1,3536.50,3536.50,0.0,...,0.0,3536.50,UPI,Processing,NaN,NaN,Patiala,Punjab,41,36-45
3,ORD0000000004,CUST00026507,PROD000213,2025-01-27,14:33:00,2025-02-02,1,34081.56,34081.56,0.0,...,50.0,34031.56,Credit Card,Delivered,NaN,NaN,Rajkot,Gujarat,29,26-35
4,ORD0000000005,CUST00009418,PROD001437,2024-06-30,07:19:00,2024-07-02,2,69021.17,138042.34,0.0,...,0.0,138042.34,UPI,Delivered,NaN,NaN,Surat,Gujarat,39,36-45

6. Clean the data

In [49]:
negative_records = df[df["Total_Amount"] <= 0]
negative_records = [["Order_ID", "Order_Value", "Shipping_Cost", "Coupon_Discount", "Total_Amount", "Order_Status"]]

In [50]:
df[df["Total_Amount"] < 0]

,Order_ID,Customer_ID,Product_ID,Order_Date,Order_Time,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,...,Coupon_Discount,Total_Amount,Payment_Mode,Order_Status,Rating,Review_Text,City,State,Customer_Age,Customer_Age_Group
84204,ORD0000084205,CUST00032702,PROD000209,2026-06-26,23:15:00,2026-07-01,1,35.57,35.57,62.36,...,100.0,-2.07,UPI,Delivered,4.0,Good product,Kanpur,UP,60,56-65
182883,ORD0000182884,CUST00012430,PROD000978,2026-01-22,19:32:00,2026-01-24,1,26.13,26.13,52.31,...,100.0,-21.56,COD,Delivered,5.0,Excellent product!,Jaipur,Rajasthan,38,36-45
207695,ORD0000207696,CUST00027671,PROD000978,2026-03-07,00:19:00,2026-03-10,1,26.13,26.13,62.56,...,100.0,-11.31,UPI,Delivered,5.0,Highly recommended!,Pune,Maharashtra,60,56-65
216234,ORD0000216235,CUST00032966,PROD000978,2025-05-19,00:46:00,2025-05-25,1,26.13,26.13,57.40,...,100.0,-16.47,COD,Delivered,4.0,Good product,Gurugram,Haryana,51,46-55
249820,ORD0000249821,CUST00010179,PROD000209,2025-03-26,07:04:00,2025-03-31,1,35.57,35.57,52.45,...,100.0,-11.98,UPI,Cancelled,NaN,NaN,Alwar,Rajasthan,43,36-45

In [51]:
df[df["Total_Amount"] >= 0].copy()

,Order_ID,Customer_ID,Product_ID,Order_Date,Order_Time,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,...,Coupon_Discount,Total_Amount,Payment_Mode,Order_Status,Rating,Review_Text,City,State,Customer_Age,Customer_Age_Group
0,ORD0000000001,CUST00014303,PROD001017,2026-06-07,08:20:00,2026-06-10,1,2622.46,2622.46,0.0,...,0.0,2622.46,COD,Delivered,NaN,NaN,Chennai,Tamil Nadu,43,36-45
1,ORD0000000002,CUST00034253,PROD000703,2025-02-04,20:05:00,2025-02-07,1,90258.00,90258.00,0.0,...,0.0,90258.00,COD,Delivered,4.0,Nice quality,Durgapur,West Bengal,22,18-25
2,ORD0000000003,CUST00000421,PROD000318,2026-03-12,14:59:00,2026-03-19,1,3536.50,3536.50,0.0,...,0.0,3536.50,UPI,Processing,NaN,NaN,Patiala,Punjab,41,36-45
3,ORD0000000004,CUST00026507,PROD000213,2025-01-27,14:33:00,2025-02-02,1,34081.56,34081.56,0.0,...,50.0,34031.56,Credit Card,Delivered,NaN,NaN,Rajkot,Gujarat,29,26-35
4,ORD0000000005,CUST00009418,PROD001437,2024-06-30,07:19:00,2024-07-02,2,69021.17,138042.34,0.0,...,0.0,138042.34,UPI,Delivered,NaN,NaN,Surat,Gujarat,39,36-45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,ORD0000249996,CUST00008137,PROD001818,2024-10-06,19:17:00,2024-10-08,1,1827.96,1827.96,0.0,...,0.0,1827.96,COD,Processing,NaN,NaN,Sohna,Haryana,37,36-45
249996,ORD0000249997,CUST00027003,PROD000955,2024-08-28,05:26:00,2024-08-31,1,4040.86,4040.86,0.0,...,0.0,4040.86,UPI,Delivered,3.0,Could be better,Mangalore,Karnataka,34,26-35
249997,ORD0000249998,CUST00027511,PROD001894,2025-12-09,13:44:00,2025-12-12,2,10516.60,21033.20,0.0,...,0.0,21033.20,UPI,Delivered,4.0,Value for money,Delhi NCR,Delhi,21,18-25
249998,ORD0000249999,CUST00022175,PROD001950,2025-05-01,18:24:00,2025-05-05,1,7847.77,7847.77,0.0,...,0.0,7847.77,UPI,Delivered,5.0,Excellent product!,Varanasi,UP,26,26-35
249999,ORD0000250000,CUST00001621,PROD001213,2025-10-28,02:01:00,2025-10-30,1,18454.82,18454.82,0.0,...,0.0,18454.82,Debit Card,Delivered,3.0,Average product,Rajkot,Gujarat,35,26-35

In [53]:
(df["Total_Amount"] < 0).sum()

5

In [54]:
df = df[df["Total_Amount"] >= 0].copy()

In [56]:
(df["Total_Amount"] < 0).sum()
df.head()

,Order_ID,Customer_ID,Product_ID,Order_Date,Order_Time,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,...,Coupon_Discount,Total_Amount,Payment_Mode,Order_Status,Rating,Review_Text,City,State,Customer_Age,Customer_Age_Group
0,ORD0000000001,CUST00014303,PROD001017,2026-06-07,08:20:00,2026-06-10,1,2622.46,2622.46,0.0,...,0.0,2622.46,COD,Delivered,NaN,NaN,Chennai,Tamil Nadu,43,36-45
1,ORD0000000002,CUST00034253,PROD000703,2025-02-04,20:05:00,2025-02-07,1,90258.00,90258.00,0.0,...,0.0,90258.00,COD,Delivered,4.0,Nice quality,Durgapur,West Bengal,22,18-25
2,ORD0000000003,CUST00000421,PROD000318,2026-03-12,14:59:00,2026-03-19,1,3536.50,3536.50,0.0,...,0.0,3536.50,UPI,Processing,NaN,NaN,Patiala,Punjab,41,36-45
3,ORD0000000004,CUST00026507,PROD000213,2025-01-27,14:33:00,2025-02-02,1,34081.56,34081.56,0.0,...,50.0,34031.56,Credit Card,Delivered,NaN,NaN,Rajkot,Gujarat,29,26-35
4,ORD0000000005,CUST00009418,PROD001437,2024-06-30,07:19:00,2024-07-02,2,69021.17,138042.34,0.0,...,0.0,138042.34,UPI,Delivered,NaN,NaN,Surat,Gujarat,39,36-45

In [58]:
df[df["Total_Amount"] < 0]

Empty DataFrame
Columns: [Order_ID, Customer_ID, Product_ID, Order_Date, Order_Time, Delivery_Date, Quantity, Unit_Price, Order_Value, Shipping_Cost, Coupon_Code, Coupon_Discount, Total_Amount, Payment_Mode, Order_Status, Rating, Review_Text, City, State, Customer_Age, Customer_Age_Group]
Index: []

[0 rows x 21 columns]

In [60]:
print("Negative Total Number:", (df["Total_Amount"] < 0).sum())
print("Rows", len(df))

Negative Total Number: 0
Rows 249995

In [63]:
df.to_csv(r"E:\data_analytics_projects\datasets\indian_e-commerce_sales\cleaned_data\sales.csv")